title = "Demo OER"
baseURL = ""
DefaultContentLanguage = "ca"
enableRobotsTXT = true

theme = "landing-uoc"

defaultContentLanguageInSubdir = true

[languages]

  [languages.ca]
    title = "Lloc web per a recursos docents i projectes"
    weight = 1
    languageName = "Catal√†"

  [languages.es]
    title = "Sitio web para recursos docentes y proyectos en abierto"
    weight = 2
    languageName = "Castellano"

  [languages.en]
    title = "Web site for open educational resources and projects"
    weight = 3
    languageName = "English"
